### ISSUE TITLE
Automatically redirect or allow download with filename

### ISSUE THREAD

**Issue by Ran-Xing** [raphaelreyna/oneshot#27]
Automatic redirection, because some websites will verify the URL

example: The URL you have entered ends in an extension that we do not support. We only accept image files that end in gz, bz2, vmdk, vhdx, qcow, qcow2, vdi, raw, img, xz. (.zip is not supported).

so i don't know what to do

**Comment by raphaelreyna** [comment]
Sorry for such a long delay in my response, but I've finally been able to dedicate some time to this project and have recently released a beta for v2. I'm not sure I entirely understand the issue here but the new beta for v2 includes a redirect command as well as a reverse proxy command. Would these maybe resolve this issue for you?
